# Generated by Django 3.1.2 on 2021-05-17 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='end_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='flight_check.airportdetails'),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='start_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flight_check.airportdetails'),
        ),
    ]
