# Generated by Django 3.1.2 on 2021-05-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_check', '0002_auto_20210518_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='flight_check.FlightDetails')),
            ],
        ),
    ]
